version: "3.8"

services:
  # web:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - main
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=444555666
    networks:
      - main
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main

networks:
  main:
    name: main
    driver: bridge

volumes:
  db:
    name: db
    driver: local
